# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblactivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityid', models.TextField(db_column='activityID')),
                ('actype', models.TextField(db_column='acType')),
                ('acname', models.TextField(db_column='acName')),
                ('acdescription', models.TextField(blank=True, db_column='acDescription', null=True)),
                ('accost', models.TextField(blank=True, db_column='acCost', null=True)),
                ('acbegintime', models.TextField(blank=True, db_column='acBeginTime', null=True)),
                ('acendtime', models.TextField(blank=True, db_column='acEndTime', null=True)),
                ('acstatus', models.TextField(blank=True, db_column='acStatus', null=True)),
                ('acdate', models.DateField(blank=True, db_column='acDate', null=True)),
                ('acrating', models.TextField(db_column='acRating')),
            ],
            options={
                'db_table': 'tblActivity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiid', models.TextField(db_column='apiID')),
                ('apisource', models.TextField(blank=True, db_column='apiSource', null=True)),
                ('apilogo', models.TextField(db_column='apiLogo')),
            ],
            options={
                'db_table': 'tblAPI',
            },
        ),
        migrations.CreateModel(
            name='Tblcity',
            fields=[
                ('cityid', models.TextField(db_column='cityID', primary_key=True, serialize=False)),
                ('cityname', models.TextField(blank=True, db_column='cityName', null=True)),
            ],
            options={
                'db_table': 'tblCity',
            },
        ),
        migrations.CreateModel(
            name='Tblcountry',
            fields=[
                ('countryid', models.TextField(db_column='countryID', primary_key=True, serialize=False)),
                ('countryname', models.TextField(blank=True, db_column='countryName', null=True)),
                ('continent', models.TextField(blank=True, null=True)),
                ('countrycode', models.TextField(blank=True, db_column='countryCode', null=True)),
            ],
            options={
                'db_table': 'tblCountry',
            },
        ),
        migrations.CreateModel(
            name='Tblcreditcard',
            fields=[
                ('creditcardnumber', models.TextField(db_column='creditCardNumber', primary_key=True, serialize=False)),
                ('creditcardcvv', models.TextField(blank=True, db_column='creditCardCVV', null=True)),
                ('creditcardexpyear', models.TextField(blank=True, db_column='creditCardExpYear', null=True)),
                ('creditcardexpdate', models.DateField(blank=True, db_column='creditCardExpDate', null=True)),
                ('creditcardtype', models.TextField(blank=True, db_column='creditCardType', null=True)),
            ],
            options={
                'db_table': 'tblCreditCard',
            },
        ),
        migrations.CreateModel(
            name='Tblcuisine',
            fields=[
                ('cuisineid', models.CharField(db_column='cuisineID', max_length=1, primary_key=True, serialize=False)),
                ('cuisine', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tblCuisine',
            },
        ),
        migrations.CreateModel(
            name='Tbldebitcard',
            fields=[
                ('debitcardnumber', models.TextField(db_column='debitCardNumber', primary_key=True, serialize=False)),
                ('debitcardexpyear', models.TextField(blank=True, db_column='debitCardExpYear', null=True)),
                ('debitcardexpdate', models.DateField(blank=True, db_column='debitCardExpDate', null=True)),
                ('debitcardtype', models.TextField(blank=True, db_column='debitCardType', null=True)),
            ],
            options={
                'db_table': 'tblDebitCard',
            },
        ),
        migrations.CreateModel(
            name='Tblhotel',
            fields=[
                ('hotelid', models.TextField(db_column='hotelID', primary_key=True, serialize=False)),
                ('hotelname', models.TextField(db_column='hotelName')),
                ('hotelphonenumber', models.TextField(blank=True, db_column='hotelPhoneNumber', null=True)),
                ('hotelwebsite', models.TextField(blank=True, db_column='hotelWebsite', null=True)),
                ('hotelrating', models.IntegerField(db_column='hotelRating')),
            ],
            options={
                'db_table': 'tblHotel',
            },
        ),
        migrations.CreateModel(
            name='Tbllocation',
            fields=[
                ('locationid', models.TextField(db_column='locationID', primary_key=True, serialize=False)),
                ('streetname', models.TextField(blank=True, db_column='streetName', null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('zipcode', models.TextField(blank=True, db_column='zipCode', null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('lcity', models.ForeignKey(blank=True, db_column='lCity', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tblcity')),
                ('lcountry', models.ForeignKey(blank=True, db_column='lCountry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tblcountry')),
            ],
            options={
                'db_table': 'tblLocation',
            },
        ),
        migrations.CreateModel(
            name='Tbloffer',
            fields=[
                ('offerid', models.CharField(db_column='offerID', max_length=1, primary_key=True, serialize=False)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('transportationtype', models.CharField(blank=True, db_column='transportationType', max_length=1, null=True)),
                ('transportationrating', models.CharField(blank=True, db_column='transportationRating', max_length=1, null=True)),
                ('restaurantname', models.CharField(blank=True, db_column='restaurantName', max_length=1, null=True)),
                ('rtcountry', models.CharField(blank=True, db_column='rtCountry', max_length=1, null=True)),
                ('rtcity', models.CharField(blank=True, db_column='rtCity', max_length=1, null=True)),
                ('rtcuisine', models.CharField(blank=True, db_column='rtCuisine', max_length=1, null=True)),
                ('rtexpense', models.CharField(blank=True, db_column='rtExpense', max_length=1, null=True)),
                ('apilogo', models.CharField(blank=True, db_column='apiLogo', max_length=1, null=True)),
                ('hotelid', models.CharField(blank=True, db_column='hotelID', max_length=1, null=True)),
                ('hotelname', models.CharField(blank=True, db_column='hotelName', max_length=1, null=True)),
                ('hotelrating', models.IntegerField(blank=True, db_column='hotelRating', null=True)),
                ('hotelcountry', models.CharField(blank=True, db_column='hotelCountry', max_length=1, null=True)),
                ('hotelcity', models.CharField(blank=True, db_column='hotelCity', max_length=1, null=True)),
                ('accountry', models.CharField(blank=True, db_column='acCountry', max_length=1, null=True)),
                ('accity', models.CharField(blank=True, db_column='acCity', max_length=1, null=True)),
                ('acname', models.CharField(blank=True, db_column='acName', max_length=1, null=True)),
                ('actype', models.CharField(blank=True, db_column='acType', max_length=1, null=True)),
                ('acrating', models.CharField(blank=True, db_column='acRating', max_length=1, null=True)),
                ('rtrating', models.CharField(blank=True, db_column='rtRating', max_length=1, null=True)),
                ('hotelexpense', models.CharField(blank=True, db_column='hotelExpense', max_length=1, null=True)),
                ('transportationcost', models.IntegerField(blank=True, db_column='transportationCost', null=True)),
                ('startdate', models.DateTimeField(blank=True, db_column='startDate', null=True)),
                ('enddate', models.DateTimeField(blank=True, db_column='endDate', null=True)),
                ('maxexpense', models.TextField(blank=True, db_column='maxExpense', null=True)),
                ('minexpense', models.TextField(blank=True, db_column='minExpense', null=True)),
                ('activityid', models.ForeignKey(blank=True, db_column='activityID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tblactivity')),
                ('apiid', models.ForeignKey(blank=True, db_column='apiID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tblapi')),
                ('destinationcity', models.ForeignKey(blank=True, db_column='destinationCity', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offer_destinationcountry', to='main.Tblcity')),
                ('destinationcountry', models.ForeignKey(blank=True, db_column='destinationCountry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offer_destinationcountry', to='main.Tblcountry')),
                ('destinylocation', models.ForeignKey(blank=True, db_column='destinyLocation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offer_destinylocation', to='main.Tbllocation')),
            ],
            options={
                'db_table': 'tblOffer',
            },
        ),
        migrations.CreateModel(
            name='Tblorder',
            fields=[
                ('orderid', models.TextField(db_column='orderID', primary_key=True, serialize=False)),
                ('ordercost', models.IntegerField(blank=True, db_column='orderCost', null=True)),
                ('orderdate', models.DateField(blank=True, db_column='orderDate', null=True)),
            ],
            options={
                'db_table': 'tblOrder',
            },
        ),
        migrations.CreateModel(
            name='Tblpayment',
            fields=[
                ('paymentid', models.TextField(db_column='paymentID', primary_key=True, serialize=False)),
                ('paymentdate', models.DateField(blank=True, db_column='paymentDate', null=True)),
                ('paymenttype', models.TextField(blank=True, db_column='paymentType', null=True)),
            ],
            options={
                'db_table': 'tblPayment',
            },
        ),
        migrations.CreateModel(
            name='Tblport',
            fields=[
                ('portname', models.TextField(db_column='portName', primary_key=True, serialize=False)),
                ('portcode', models.TextField(blank=True, db_column='portCode', null=True)),
                ('portlocation', models.ForeignKey(blank=True, db_column='portLocation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tbllocation')),
            ],
            options={
                'db_table': 'tblPort',
            },
        ),
        migrations.CreateModel(
            name='Tblpreference',
            fields=[
                ('preferenceid', models.TextField(db_column='preferenceID', primary_key=True, serialize=False)),
                ('preferencetype', models.TextField(blank=True, db_column='preferenceType', null=True)),
            ],
            options={
                'db_table': 'tblPreference',
            },
        ),
        migrations.CreateModel(
            name='Tblreservation',
            fields=[
                ('reservationid', models.TextField(db_column='reservationID', primary_key=True, serialize=False)),
                ('reservationtype', models.TextField(blank=True, db_column='reservationType', null=True)),
            ],
            options={
                'db_table': 'tblReservation',
            },
        ),
        migrations.CreateModel(
            name='Tblrestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantid', models.TextField(db_column='restaurantID')),
                ('restaurantname', models.TextField(db_column='restaurantName')),
                ('rtphonenumber', models.TextField(blank=True, db_column='rtPhoneNumber', null=True)),
                ('rtcuisine', models.TextField(db_column='rtCuisine')),
                ('rtrating', models.TextField(db_column='rtRating')),
                ('cuisineid', models.ForeignKey(blank=True, db_column='cuisineID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tblcuisine')),
                ('rtaddress', models.ForeignKey(blank=True, db_column='rtAddress', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tbllocation')),
                ('rtcity', models.ForeignKey(db_column='rtCity', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tblcity')),
                ('rtcountry', models.ForeignKey(db_column='rtCountry', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tblcountry')),
            ],
            options={
                'db_table': 'tblRestaurant',
            },
        ),
        migrations.CreateModel(
            name='Tbltransportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportationid', models.TextField(db_column='transportationID')),
                ('transportationtype', models.TextField(db_column='transportationType')),
                ('departureport', models.TextField(db_column='departurePort')),
                ('destinationport', models.TextField(db_column='destinationPort')),
                ('terminal', models.TextField(blank=True, null=True)),
                ('tripstatus', models.TextField(blank=True, db_column='tripStatus', null=True)),
                ('tripnumber', models.TextField(blank=True, db_column='tripNumber', null=True)),
                ('sitnumber', models.TextField(blank=True, db_column='sitNumber', null=True)),
                ('departuretime', models.DateTimeField(blank=True, db_column='departureTime', null=True)),
                ('arrivedtime', models.DateTimeField(blank=True, db_column='arrivedTime', null=True)),
            ],
            options={
                'db_table': 'tblTransportation',
            },
        ),
        migrations.CreateModel(
            name='Tbltransportationcompany',
            fields=[
                ('name', models.TextField(db_column='Name')),
                ('transportationcompanyid', models.TextField(db_column='transportationCompanyID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbltransportationCompany',
            },
        ),
        migrations.CreateModel(
            name='Tbluser',
            fields=[
                ('userid', models.TextField(db_column='userID', primary_key=True, serialize=False)),
                ('firstname', models.TextField(blank=True, db_column='firstName', null=True)),
                ('lastname', models.TextField(blank=True, db_column='lastName', null=True)),
                ('useremail', models.TextField(blank=True, db_column='userEmail', null=True)),
                ('userphonenumber', models.TextField(blank=True, db_column='userPhoneNumber', null=True)),
                ('userbirthdate', models.DateField(blank=True, db_column='userBirthdate', null=True)),
                ('usergender', models.TextField(blank=True, db_column='userGender', null=True)),
                ('useraddress', models.IntegerField(blank=True, db_column='userAddress', null=True)),
                ('password', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblUser',
            },
        ),
        migrations.AddField(
            model_name='tbltransportation',
            name='companyid',
            field=models.ForeignKey(blank=True, db_column='companyID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tbltransportationcompany'),
        ),
        migrations.AddField(
            model_name='tbltransportation',
            name='portid',
            field=models.ForeignKey(blank=True, db_column='portID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tblport'),
        ),
        migrations.AddField(
            model_name='tblorder',
            name='reservationid',
            field=models.ForeignKey(blank=True, db_column='reservationID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tblreservation'),
        ),
        migrations.AddField(
            model_name='tblorder',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tbluser'),
        ),
        migrations.AddField(
            model_name='tbloffer',
            name='restaurantid',
            field=models.ForeignKey(blank=True, db_column='restaurantID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tblrestaurant'),
        ),
        migrations.AddField(
            model_name='tbloffer',
            name='sourcecity',
            field=models.ForeignKey(blank=True, db_column='sourceCity', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offer_sourcecity', to='main.Tblcity'),
        ),
        migrations.AddField(
            model_name='tbloffer',
            name='sourcecountry',
            field=models.ForeignKey(blank=True, db_column='sourceCountry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offer_sourcecountry', to='main.Tblcountry'),
        ),
        migrations.AddField(
            model_name='tbloffer',
            name='sourcelocation',
            field=models.ForeignKey(blank=True, db_column='sourceLocation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offer_sourcelocation', to='main.Tbllocation'),
        ),
        migrations.AddField(
            model_name='tbloffer',
            name='transportationid',
            field=models.ForeignKey(blank=True, db_column='transportationID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tbltransportation'),
        ),
        migrations.AddField(
            model_name='tblhotel',
            name='hoteladdress',
            field=models.ForeignKey(blank=True, db_column='hotelAddress', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tbllocation'),
        ),
        migrations.AddField(
            model_name='tblhotel',
            name='hotelcity',
            field=models.ForeignKey(db_column='hotelCity', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tblcity'),
        ),
        migrations.AddField(
            model_name='tblhotel',
            name='hotelcountry',
            field=models.ForeignKey(db_column='hotelCountry', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tblcountry'),
        ),
        migrations.AddField(
            model_name='tbldebitcard',
            name='debitcardowner',
            field=models.ForeignKey(blank=True, db_column='debitCardOwner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tbluser'),
        ),
        migrations.AddField(
            model_name='tblcreditcard',
            name='creditcardowner',
            field=models.ForeignKey(blank=True, db_column='creditCardOwner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tbluser'),
        ),
        migrations.AddField(
            model_name='tblcity',
            name='countryid',
            field=models.ForeignKey(blank=True, db_column='countryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tblcountry'),
        ),
        migrations.AlterUniqueTogether(
            name='tblapi',
            unique_together=set([('apiid', 'apilogo')]),
        ),
        migrations.AddField(
            model_name='tblactivity',
            name='aclocation',
            field=models.ForeignKey(blank=True, db_column='aclocation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Tbllocation'),
        ),
    ]
