# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-30 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblactivity',
            name='acrating',
            field=models.TextField(db_column='acRating', null=True),
        ),
    ]
