# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-10 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161030_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblreservation',
            name='actitinerary',
            field=models.TextField(blank=True, db_column='actitinerary', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='actprice',
            field=models.TextField(blank=True, db_column='actprice', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='adult',
            field=models.TextField(blank=True, db_column='adult', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='budget',
            field=models.TextField(blank=True, db_column='budget', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='children',
            field=models.TextField(blank=True, db_column='children', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='destination',
            field=models.TextField(blank=True, db_column='destination', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='enddate',
            field=models.TextField(blank=True, db_column='enddate', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='hoteladdress',
            field=models.TextField(blank=True, db_column='hoteladdress', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='hotelname',
            field=models.TextField(blank=True, db_column='hotelname', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='hotelprice',
            field=models.TextField(blank=True, db_column='hotelprice', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='hotelroomdescription',
            field=models.TextField(blank=True, db_column='hotelroomdescription', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='origin',
            field=models.TextField(blank=True, db_column='origin', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='preference',
            field=models.TextField(blank=True, db_column='preference', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='rating',
            field=models.TextField(blank=True, db_column='rating', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='startdate',
            field=models.TextField(blank=True, db_column='startdate', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='transportationinfo',
            field=models.TextField(blank=True, db_column='transportationinfo', null=True),
        ),
        migrations.AddField(
            model_name='tblreservation',
            name='user',
            field=models.TextField(blank=True, db_column='user', null=True),
        ),
    ]
