# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-10 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161210_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblreservation',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='tblreservation',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='tblreservation',
            name='children',
        ),
        migrations.RemoveField(
            model_name='tblreservation',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='tblreservation',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='tblreservation',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='tblreservation',
            name='startdate',
        ),
    ]
